version: '3.4'

services:
  envoy:
   image: envoyproxy/envoy:v1.23-latest

  opa:
   image: openpolicyagent/opa:latest-envoy

  mock-api:
    image: mock-api
    build:
      context: .
      dockerfile: mock-api/Dockerfile

